// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Motor Controller State Machine for TV Slider
// Generated by StateSmith
// Event-driven architecture

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h>
#include <stdbool.h>
#include "slider_types.h"


typedef enum slider_state_machine_EventId
{
    slider_state_machine_EventId_CMD_CLEAR_FAULT = 0,
    slider_state_machine_EventId_CMD_MOVE_IN = 1,
    slider_state_machine_EventId_CMD_MOVE_OUT = 2,
    slider_state_machine_EventId_CMD_STOP = 3,
    slider_state_machine_EventId_MOTOR_FAULT = 4,
    slider_state_machine_EventId_SENSOR_IN_SLOW = 5,
    slider_state_machine_EventId_SENSOR_IN_STOP = 6,
    slider_state_machine_EventId_SENSOR_OUT_SLOW = 7,
    slider_state_machine_EventId_SENSOR_OUT_STOP = 8,
    slider_state_machine_EventId_TIMER_EXPIRED = 9
} slider_state_machine_EventId;

enum
{
    slider_state_machine_EventIdCount = 10
};

typedef enum slider_state_machine_StateId
{
    slider_state_machine_StateId_ROOT = 0,
    slider_state_machine_StateId_ERROR_STATE = 1,
    slider_state_machine_StateId_MOVING_IN_STATE = 2,
    slider_state_machine_StateId_IN_FULL_SPEED_STATE = 3,
    slider_state_machine_StateId_IN_RAMP_DOWN_STATE = 4,
    slider_state_machine_StateId_IN_RAMP_UP_STATE = 5,
    slider_state_machine_StateId_MOVING_OUT_STATE = 6,
    slider_state_machine_StateId_OUT_FULL_SPEED_STATE = 7,
    slider_state_machine_StateId_OUT_RAMP_DOWN_STATE = 8,
    slider_state_machine_StateId_OUT_RAMP_UP_STATE = 9,
    slider_state_machine_StateId_STOPPED_STATE = 10
} slider_state_machine_StateId;

enum
{
    slider_state_machine_StateIdCount = 11
};


// Generated state machine
// forward declaration
typedef struct slider_state_machine slider_state_machine;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct slider_state_machine_Vars
{
    uint16_t speed;               // current motor speed
} slider_state_machine_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void slider_state_machine_ctor(slider_state_machine* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void slider_state_machine_start(slider_state_machine* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void slider_state_machine_dispatch_event(slider_state_machine* sm, slider_state_machine_EventId event_id);

// Thread safe.
char const * slider_state_machine_state_id_to_string(slider_state_machine_StateId id);

// Thread safe.
char const * slider_state_machine_event_id_to_string(slider_state_machine_EventId id);

// Generated state machine
struct slider_state_machine
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    slider_state_machine_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    slider_state_machine_Vars vars;
};

