env:
  node: true
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - react
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-explicit-any': off
  no-unused-vars: off #This one is covered by below
  '@typescript-eslint/no-unused-vars':
    [
      error,
      {
        'argsIgnorePattern': '^_',
        'varsIgnorePattern': '^_',
        'caughtErrorsIgnorePattern': '^_'
      }
    ]
  import/no-unresolved: 'error'
  react/jsx-no-undef: [2, { 'allowGlobals': true }]
globals:
  Router: readonly
settings:
  react:
    version: 'detect'
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './']
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json
  import/parsers:
    '@typescript-eslint/parser': ['.ts', '.tsx']
